### ISSUE TITLE
Plant API Calls

### ISSUE THREAD

**Issue by tjpenc** [tjpenc/PlantsFE#19]
In the application, several API calls are needed to retrieve and modify plants in the database. This application needs a call to:

Get Plants
Return an array of all of a users plants
Needs a uid to identify the correct user in the backend

Get Single Plant
Return a single plant object for a user
Needs to pass id to backend to grab the appropriate task

Create Plant
Creates a new plant associated with a user
Needs to pass through the following information to the backend:
uid
name
description
type
isOwned
isPlanted
numberPerSquare
plantImage
symbol

Update Plant 
Allows user to update a pre-existing plant
Needs to pass id to backend to identify the correct plant in the database
Must be able to handle the change of the following information, and pass it to the backend:
name
description
type
isOwned
numberPerSquare
plantImage
symbol

Delete Plant
Allows user to delete a plant they have created
Needs to pass an id to the backend to identify the correct plant in the database

**Comment by rohit-chaware** [comment]
Hey @tjpenc I would like to work on this issue.
